### PR TITLE
Remove cert-manager

### PR DESCRIPTION
**Pull request by gytis**

### CODE REVIEW

**Comment by gytis** [comment]
I'm not sure this is enough. People could still find the certificate in the history. Any suggestions how to safely and permanently remove these files?

**Comment by geoand** [comment]
Is there a catch to this :P ? Seems to deceptively simple :P

**Comment by geoand** [comment]
@gytis We could force push to master :)

**Comment by gytis** [comment]
Catch to what? I forgot about force push, I was a diligent github user for a while now and didn't do such nasty actions :D

**Comment by geoand** [comment]
There is a use for everything I guess :).

If would force push if I were you, there is minimal chance of problems I would say

**Comment by gytis** [comment]
@cmoulliard are you ok with me removing all of your cert-manager commits?

**Comment by cmoulliard** [comment]
LGTM

**Comment by gytis** [comment]
Removed the commits, closing this PR.

**Pull request closed without merging**
